### ISSUE TITLE
endless loop in query evaluation

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strus#53]
One thread in 100% CPU:

```
#0  0x004b1a43 in strus::IteratorUnion::skipDoc(int const&) () from /usr/lib/strus/libstrus_queryproc.so.0.8
#1  0x0054abd0 in strus::Accumulator::nextRank(int&, unsigned int&, float&) ()
   from /usr/lib/strus/libstrus_queryeval.so.0.8
#2  0x00543354 in strus::Query::evaluate() () from /usr/lib/strus/libstrus_queryeval.so.0.8
#3  0x08076acf in apps::query::query_cmd (this=0x9baa0a4, name="teste", qry="", query_in_url=false)
    at /data/b/aba/strusWebService/src/query.cpp:270
#4  0x08077673 in apps::query::query_payload_cmd (this=0x9baa0a4, name="teste")
    at /data/b/aba/strusWebService/src/query.cpp:46
#5  0x08077e43 in operator() (this=0x9bac710, a1="teste") at /usr/include/cppcms/url_dispatcher.h:233
#6  callable_impl<void, cppcms::url_dispatcher::binder1<apps::query> >::call (this=0x9bac710, a1="teste")
    at /usr/include/booster/function.h:178
#7  0x0062ca6f in ?? () from /usr/lib/libcppcms.so.1
#8  0x0062c1bb in cppcms::url_dispatcher::dispatch(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libcppcms.so.1
#9  0x00627443 in cppcms::application::main(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libcppcms.so.1
#10 0x0062110a in cppcms::http::context::dispatch(booster::intrusive_ptr<cppcms::application>, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) () from /usr/lib/libcppcms.so.1
#11 0x00622738 in booster::function<void ()()>::callable_impl<void, cppcms_boost::_bi::bind_t<void, void (*)(booster::intrusive_ptr<cppcms::application>, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool), cppcms_boost::_bi::list3<cppcms_boost::_bi::value<booster::intrusive_ptr<cppcms::application> >, cppcms_boost::_bi::value<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, cppcms_boost::_bi::value<bool> > > >::call() () from /usr/lib/libcppcms.so.1
#12 0x00624237 in cppcms::impl::thread_pool::worker() () from /usr/lib/libcppcms.so.1
#13 0x00623f6e in booster::function<void ()()>::callable_impl<void, cppcms_boost::_bi::bind_t<void, cppcms_boost::_mfi::mf0<void, cppcms::impl::thread_pool>, cppcms_boost::_bi::list1<cppcms_boost::_bi::value<cppcms::impl::thread_pool*> > > >::call() () from /usr/lib/libcppcms.so.1
#14 0x00b8e41a in booster_thread_func () from /usr/lib/libbooster.so.0
#15 0x00419bc9 in start_thread () from /lib/libpthread.so.0
```

A `fini` never returns. Trying to hunt if this is a corruption in my search index or actually a bug
in the union iterator.

**Comment by andreasbaumann** [comment]
strus version is 0.8.2

**Comment by andreasbaumann** [comment]
recreated the test index, doesn't seem to be the problem.

**Comment by andreasbaumann** [comment]
A clue could be that there are 49 terms in the operator..

**Comment by patrickfrey** [comment]
Fixed. union operator was broken. Puzzle why this was not detected by the randoc test.

**Comment by patrickfrey** [comment]
Implemented a test for it, that is calculating the erathostenes sieve as union of 61 iterators on numbers that are a multiplication of a base number and verifying the result with a function enumerating some prime numbers.

**Comment by andreasbaumann** [comment]
tested with 10x10 = 100 features in one operator. Works.
